name: flutter_blue_ultra_example
description: Demonstrates how to use the flutter_blue_ultra plugin.

publish_to: 'none'

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_ultra:
    path: ../
  flutter_blue_ultra_design_system:
    path: ../../flutter_blue_ultra_design_system

  permission_handler: 12.0.1
  device_info_plus: 13.1.0
  flutter_bloc: 9.1.1
  equatable: 2.0.8

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_blue_ultra_android:
    path: ../../flutter_blue_ultra_android
  flutter_blue_ultra_darwin:
    path: ../../flutter_blue_ultra_darwin
  flutter_blue_ultra_linux:
    path: ../../flutter_blue_ultra_linux
  flutter_blue_ultra_platform_interface:
    path: ../../flutter_blue_ultra_platform_interface
  flutter_blue_ultra_web:
    path: ../../flutter_blue_ultra_web
  flutter_blue_ultra_accessory_setup:
    path: ../../flutter_blue_ultra_accessory_setup

flutter:
  uses-material-design: true
